blank_issues_enabled: false
contact_links:
  - name: Question or Discussion
    url: https://github.com/vickerdent/video-streamer-server/discussions
    about: Ask questions or discuss ideas with the community
  - name: Documentation
    url: https://github.com/vickerdent/video-streamer-server/tree/main/docs
    about: Check the documentation for help